title: Eivind Moe Hammersmark
author: Eivind Moe Hammersmark
contact: e.m.hammersmark [at] econ.uio.no
cv: files/CV.pdf
description:
  This page contains links to research, and replication code for published papers.
about_me:
  PhD economist, Senior Lecturer at <a href="https://www.sv.uio.no/econ/">University of Oslo Department of Economics</a>, doing research on foreign aid, economic development, conflict, natural resources.
google_analytics: UA-44788563-1
show_downloads: false
theme: jekyll-theme-minimal
