title: Eivind Hammersmark
author: Eivind Hammersmark
contact: eivindhammers [at] gmail.com
cv: files/CV.pdf
description:
  This page contains links to research, and replication code for published papers.
about_me:
  PhD economist, Senior Adviser at <a href="https://norad.no">Norad</a>. Research interests include subnational and historical aspects of economic development, conflict and natural resources.
google_analytics: UA-44788563-1
show_downloads: false
theme: jekyll-theme-minimal
